### ISSUE TITLE
'highlight.js/lib/common' does not exist

### ISSUE THREAD

**Issue by jannikbuscha** [highlightjs/vue-plugin#16] opened 2021-09-18 16:42 UTC
'highlight.js/lib/common' does not exist:
![image](https://user-images.githubusercontent.com/74017697/133895869-400742a8-78a4-4981-a5cf-a66a7cf3fb1a.png)
![image](https://user-images.githubusercontent.com/74017697/133895874-767adee8-cf69-41c6-9c23-b5fc1d899869.png)

To fix the error in the docu, the following must be imported:
`import hljs from "@highlightjs/vue-plugin/node_modules/highlight.js/lib/common";`

![image](https://user-images.githubusercontent.com/74017697/133895981-f439cc14-33df-4dfe-ae78-daf2c6e3e79f.png)

You also need to import the styling:
`@import "./node_modules/@highlightjs/vue-plugin/node_modules/highlight.js/scss/base16/darcula";`

highlight.js in the node modules is also useless.

**Comment by joshgoebel** [comment] 2021-09-19 08:05
> 'highlight.js/lib/common' does not exist:

It most certainly does in the latest release.  I think the issue is your non-vue vendored version is older?

> You also need to import the styling:

If we don't document this it could certainly be added to the README. PR welcome.

> highlight.js in the node modules is also useless.

Huh?

**Comment by joshgoebel** [comment] 2021-09-19 08:14
If the answer here isn't sufficient I'm guessing this should also be closed by #17?  If not please continue the conversation and we'll see what we can do to help! Thanks.

**Closed by joshgoebel** 2021-09-19 08:14 UTC

**Comment by jannikbuscha** [comment] 2021-09-19 15:05
> > 'highlight.js/lib/common' does not exist:
> 
> It most certainly does in the latest release. I think the issue is your non-vue vendored version is older?
> 
> > You also need to import the styling:
> 
> If we don't document this it could certainly be added to the README. PR welcome.
> 
> > highlight.js in the node modules is also useless.
> 
> Huh?

I have expressed myself somewhat unclearly. I just meant that highlights.js is unnecessary as an additional dependency in the node modules, but the fix with the peer dependency should have fixed that
